name: VNC with Firefox and Cloudflared

on: [push]

jobs:
  setup-vnc:
    runs-on: ubuntu-latest

    steps:
      # 1. 检出代码
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. 安装依赖
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget
      - uses: wangsijie/setup-v2ray@v1
        with:
          config-base64: ${{ secrets.CONFIG }}
      - run: curl https://api.live.bilibili.com/ip_service/v1/ip_service/get_ip_addr # see if it is the proxy server's ip
        env:
          http_proxy: "127.0.0.1:1080"  
          
